### ISSUE TITLE
Could you help me

### ISSUE THREAD

**Issue by ayasystems** [8bitmcu/esphome_tpms#1]
I've testing your code with my TMPS device

I see 0303A5270308425208FF281D100143342D raw data with BLE Scanner

![image](https://github.com/8bitmcu/ESPHome_BLE_TPMS/assets/7864168/52bada2b-2f96-41da-a5b7-dfd341ee997b)

![image](https://github.com/8bitmcu/ESPHome_BLE_TPMS/assets/7864168/e5a3f869-1207-4340-b1b0-1c7f4368871a)

Pressure seems be not working fine

![image](https://github.com/8bitmcu/ESPHome_BLE_TPMS/assets/7864168/a260ae82-2c63-4cb4-9afd-b64eefaf7bf3)

Regards!!

**Comment by 8bitmcu** [comment]
Hi there, I'll try my best to help out!

The third screenshot, where the pressure shows 0.3, is that with running the code from this github repository?

Could you run the following code on an ESP32 BLE device and report back with the output?

```
esp32_ble_tracker:
  on_ble_advertise:
    - mac_address: "70:18:6C:DE:5C:F3"
      then:
        - lambda: |-
            ESP_LOGD("BLE_TPMS", "TPMS BLE Device discovered");
            for (auto data : x.get_manufacturer_datas()) {
              ESP_LOGD("BLE_TPMS", "Manufacturer ID: %s", data.uuid.to_string().c_str());
              ESP_LOGD("BLE_TPMS", "Manufacturer Data: %X:%X:%X:%X:%X", data.data[0], data.data[1], data.data[2], data.data[3], data.data[4]);
              ESP_LOGD("BLE_TPMS", "Manufacturer Data length: %d", data.data.size());
            }
```

Also, does all four sensors start with the MAC 70:18:6C? They seem different from mine, but if you can already read the temperature and voltage okay, I think it would be relatively easy to fix the pressure readings.


Vincent

**Comment by ayasystems** [comment]
Hi, thanks for your reply

```
[D][BLE_TPMS:063]: TPMS BLE Device discovered
[D][BLE_TPMS:065]: Manufacturer ID: 0x1E28
[D][BLE_TPMS:066]: Manufacturer Data: 10:1:48:35:17
[D][BLE_TPMS:067]: Manufacturer Data length: 5
```

Android APP is showing 1.3 BAR of pressure

My MACs are:
  mac_front: 38:A8:00:00:C2:43
  mac_rear: 38:AB:00:00:98:23

Regards!

**Comment by ayasystems** [comment]
0303A527 03084252 08FF281D10**0143**342D
 

 
0143 (PSI)
0143 to dec (323)
(323-145)/145 = 1,22 bar 
seems be correct 1.22 is showed by APP 

I got the info from here -> https://github.com/andi38/TPMS/blob/main/tpms-bluepy.py

**Comment by 8bitmcu** [comment]
Good find! Thanks for getting back to me with the solution. I've added a link to that repository in my readme, hopefully it helps others as well!

**Comment by AgentP2** [comment]
I have the same problem (tyre pressure is not correct): 
0303A527 03084252 08FF801D100304E058
MAC: 3B:70:00

I don't know how to adjust the code to get the correct value. 
@8bitmcu or @ayasystems 
How do I adjust the code?
